### PR TITLE
Adds peak hold feature

### PR DESCRIPTION
**Pull request by henrikssn**
The idea is to store the maximum value recorded to allow picking up short transmissions. You enable it with the H key and disable with h (which will also clear the peak hold value).

I used it for TX antenna tuning yesterday by sweeping the frequency with my transmitter and looking at the peak hold chart from retroscope. You can then easily spot the resonance frequency and adjust accordingly.

### CODE REVIEW

**Review by r4d10n — APPROVED** [review]

**Comment by r4d10n** [comment]
Thanks Eric for the commit! Glad to know you could use it for your antenna tuning...

**Comment by alphafox02** [comment]
Would it be possible to add this to the soapy version? I’m building it directly into the PlutoSDR firmware and would love to include as many features as possible.

**Comment by r4d10n** [comment]
Done and updated to SoapySDR API 0.8.

**Comment by alphafox02** [comment]
Awesome thank you!

**Comment by alphafox02** [comment]
Sorry one additional question, would the soapy build though be what I use in buildroot to build and run directly on the PlutoSDR? I was thinking I should be using the retrogram Pluto build. I do have soapysdr and soapy v8 built in and running directly on the Pluto.

**Comment by r4d10n** [comment]
For bundling in PlutoSDR, [retrogram-plutosdr](https://github.com/r4d10n/retrogram-plutosdr) would be the better fit, since it uses native iio libraries. You would have to include the terminfo file as documented in the readme. Peak-hold feature has been included now and the arm binary is updated.

**Comment by alphafox02** [comment]
Just tested after following directions, working great directly on the PlutoSDR! Peak hold and all. Thank you.

**Pull request merged**
